/*
 * AboutDyneticaPanel.java
 *
 * Created on August 28, 2001, 10:19 AM
 */

package dynetica.gui;

/**
 * 
 * @author Lingchong You
 * @version 1.0
 */
public class AboutDyneticaFrame extends javax.swing.JFrame {

    /** Creates new form AboutDyneticaPanel */
    public AboutDyneticaFrame() {
        initComponents();
        setSize(500, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> About <i> <b> Dynetica </i> </b>");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jTextPane1.setEditable(false);
        jTextPane1.setText("Thank you for using Dynetica.\n\nDynetica is a generic model building tool for DYNamic NETworks that\nexist in nature, such as the chemical reaction networks, \nmetabolic networks, signalling pathways, and genetic networks.\n\nMore detailed help documentation is under construction.\n\nCopyright (C) 1999-2013  Lingchong You Lab (contact: you@duke.edu).\nAll rights reserved.\n\nCredits: \nApirak Hoolar (2001-2002),  extended and improved the mathmatical expression parser\nDerek Eidum (2013), introduced dynetica.objective package and the ability to do parameter search by various algorithms\nKanishk Asthana (2013), introduced modular systems and improved network visualization.\nXizheng (Billy) Wan (2016), extended the initial value field in sensitivity analysis and introduced invasion simulation and evolutionary dynamics simulation.\n");
        jTextPane1.setMinimumSize(new java.awt.Dimension(482, 261));
        jScrollPane3.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }// GEN-LAST:event_jButton2ActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_exitForm
        this.dispose();
    }// GEN-LAST:event_exitForm

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
