/*
 * ExpressionEditor.java
 *
 * Created on April 19, 2005, 1:22 AM
 */

package dynetica.gui.entities;

/**
 *
 * @author  Lingchong You
 * @version 1.2
 */
public class ExpressionEditor extends javax.swing.JPanel {

    dynetica.entity.ExpressionVariable expression;
    /** Creates new customizer expressionCustomizer */
    public ExpressionEditor(dynetica.entity.ExpressionVariable e) {
        expression = e;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        labelPanel = new javax.swing.JPanel();
        valueLabel = new javax.swing.JLabel();
        fieldPanel = new javax.swing.JPanel();
        valueField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        annotationArea = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(100000, 1000000));
        setMinimumSize(new java.awt.Dimension(106, 100));
        setPreferredSize(new java.awt.Dimension(250, 270));
        setLayout(new java.awt.BorderLayout(0, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html> <i> Expression </i>" + expression.getName());
        jLabel2.setMaximumSize(new java.awt.Dimension(176, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(176, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(176, 30));
        add(jLabel2, java.awt.BorderLayout.NORTH);

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setDividerSize(3);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setPreferredSize(new java.awt.Dimension(245, 250));

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(243, 100));

        labelPanel.setLayout(new java.awt.GridLayout(1, 1, 1, 1));

        valueLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        valueLabel.setText("Expression");
        valueLabel.setMaximumSize(new java.awt.Dimension(100, 25));
        valueLabel.setMinimumSize(new java.awt.Dimension(100, 25));
        valueLabel.setPreferredSize(new java.awt.Dimension(100, 25));
        labelPanel.add(valueLabel);

        jSplitPane1.setLeftComponent(labelPanel);

        fieldPanel.setMaximumSize(new java.awt.Dimension(150, 100));
        fieldPanel.setLayout(new java.awt.GridLayout(1, 1, 1, 1));

        valueField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        valueField.setText(expression.getExpressionString());
        valueField.setMaximumSize(new java.awt.Dimension(150, 25));
        valueField.setMinimumSize(new java.awt.Dimension(106, 25));
        valueField.setPreferredSize(new java.awt.Dimension(106, 25));
        valueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueFieldActionPerformed(evt);
            }
        });
        valueField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valueFieldFocusLost(evt);
            }
        });
        fieldPanel.add(valueField);

        jSplitPane1.setRightComponent(fieldPanel);

        jSplitPane2.setLeftComponent(jSplitPane1);

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Annotation"));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(103, 80));

        annotationArea.setLineWrap(true);
        annotationArea.setText(expression.getAnnotation());
        annotationArea.setWrapStyleWord(true);
        annotationArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        annotationArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                annotationAreaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(annotationArea);

        jSplitPane2.setRightComponent(jScrollPane1);

        add(jSplitPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void annotationAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_annotationAreaFocusLost
      setAnnotation();
    }//GEN-LAST:event_annotationAreaFocusLost

  private void valueFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valueFieldFocusLost
    setExpression();
  }//GEN-LAST:event_valueFieldFocusLost

  private void valueFieldHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_valueFieldHierarchyChanged
    setExpression();
  }//GEN-LAST:event_valueFieldHierarchyChanged

  private void valueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueFieldActionPerformed
    setExpression();
  }//GEN-LAST:event_valueFieldActionPerformed

  private void setAnnotation() {
     String newAnnotation = annotationArea.getText();
     String oldOne = expression.getAnnotation();
     if (oldOne.compareTo(newAnnotation) != 0) {
         expression.getSystem().fireSystemStateChange();
         expression.setAnnotation(newAnnotation);
     }
  }

  private void setExpression() {
      String oldExpr= expression.toString();
      String newExpr = valueField.getText();
      if (oldExpr != newExpr) {
          expression.setExpression(newExpr);
       }
  }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea annotationArea;
    private javax.swing.JPanel fieldPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JTextField valueField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
