/*
 * FigureWindow.java
 *
 * Created on August 13, 2001, 9:56 PM
 * Revised 4/19/2005 Lingchong You
 */

package dynetica.gui.plotting;

/**
 *
 * @author  Lingchong You
 * @version 0.1
 */
import dynetica.system.*;
import dynetica.entity.*;
import dynetica.util.DyneticaProperties;
import java.util.*;
import javax.swing.*;
import java.io.File;

public class FigureWindow extends javax.swing.JFrame {
    Figure figure = new Figure();
    final DefaultListModel substanceNames = new DefaultListModel();
    final dynetica.system.ReactiveSystem system;
    FigureAxisModel figureAxisModel;
    AutoUpdateThread autoUpdateThread = new AutoUpdateThread();
    
    //
    // Constructs a FigureWindow that plots data directly from
    // a ReactiveSystem
    //
    public FigureWindow(dynetica.system.ReactiveSystem system) {
        super("Time courses for ReactiveSystem " + system.getName());
        this.system = system;
        List substances = system.getSubstances();
        int nSubs = substances.size(); //substances.length;
        System.out.println("# of substances = " + nSubs);
        Substance s;
        for (int i = 0; i < nSubs; i ++) {
            s = (Substance) (substances.get(i));
            substanceNames.addElement(s.getName());
        }
        initComponents ();
        figurePanel.add(figure, java.awt.BorderLayout.CENTER);
        if (autoUpdateBox.getState()) {
           autoUpdateThread.start();
       }
       else {
          updateFigure();
       }
       pack ();
    }
    
    public void setUpData() {
        List substances = system.getSubstances();
        int nSubs = substances.size(); //substances.length;
        System.out.println("# of substances = " + nSubs);
        Substance s;
        for (int i = 0; i < nSubs; i ++) {
            s = (Substance) (substances.get(i));
            substanceNames.addElement(s.getName());
        }
        figure.setSize(400, 300);
    }
    
    public void updateFigure() {
        List substances = system.getSubstances();
        double [] completeXvalues = system.getTimer().getTimePoints();
        int nTotalPoints = completeXvalues.length;
        int [] indices = substanceList.getSelectedIndices();
        
        //
        // if the total number of time points exceeds maxDataPoints, sample only
        // maxDataPoints of data points out the time courses.
        //
        int dataPoints = Math.min (nTotalPoints, maxDataPoints);
        
        double samplingStep = (double) nTotalPoints / dataPoints;
        
        double [] xValues = new double [dataPoints];
        double [][] yValues = new double[indices.length][dataPoints];
        String [] labels = new String[indices.length];
        
        for (int j = 0; j < dataPoints; j++) {
            xValues[j] = completeXvalues[(int) Math.floor(j * samplingStep)];
        }
        
        for (int i = 0; i < indices.length; i ++) {
//            System.out.println(indices[i]);
            Substance s = (Substance) ( substances.get(indices[i]));
            for (int j = 0; j < dataPoints; j ++) {
                double sj =  s.getValues() [(int) Math.floor(j * samplingStep)];
                yValues[i][j] = sj;                
            }
            //
            // the following code may result in corrupted data
            //
            // yValues[i] = s.getValues();
            //
            // The reason is as follows: while this method is attempting to get data
            // from system, the running simulation may have changed the system in
            // the meantime. As a result, the length of s.getValues() may be longer
            // than nPoints.
            //
            labels[i] = (String) ( substanceNames.get(indices[i]));
        }
        
        
        
        figure.setData("Time", labels, xValues, yValues);
        figure.setLogX(logXItem.getState());
        figure.setLogY(logYItem.getState());
        figure.repaint();
        if (figureAxisModel == null) {
            figureAxisModel = new FigureAxisModel();
            rangeTable.setModel(figureAxisModel);
        }
        else
           figureAxisModel.setFigure();
        
        processBar.setValue(nTotalPoints);
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        substanceList = new javax.swing.JList();
        substanceListLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rangeTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        logXbox = new javax.swing.JCheckBox();
        logYbox = new javax.swing.JCheckBox();
        figurePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        processBar = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maxPointsSlider = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveSelectedDataItem = new javax.swing.JMenuItem();
        closeItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        simMenu = new javax.swing.JMenu();
        startItem = new javax.swing.JMenuItem();
        pauseItem = new javax.swing.JMenuItem();
        resumeItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        logXItem = new javax.swing.JCheckBoxMenuItem();
        logYItem = new javax.swing.JCheckBoxMenuItem();
        selectAllItem = new javax.swing.JMenuItem();
        autoUpdateBox = new javax.swing.JCheckBoxMenuItem();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mainPane.setDividerLocation(110);
        mainPane.setLastDividerLocation(10);
        mainPane.setPreferredSize(new java.awt.Dimension(500, 400));

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLastDividerLocation(80);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(60, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(60, 200));

        substanceList.setModel(substanceNames);
        substanceList.setSelectedIndex(0);
        substanceList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                substanceListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(substanceList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        substanceListLabel.setText("Substances");
        jPanel2.add(substanceListLabel, java.awt.BorderLayout.NORTH);

        jSplitPane1.setTopComponent(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout(0, 3));

        jLabel6.setText("Figure Configuration");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 18));
        jLabel6.setPreferredSize(new java.awt.Dimension(110, 18));
        jPanel3.add(jLabel6, java.awt.BorderLayout.NORTH);

        rangeTable.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        rangeTable.setMaximumSize(new java.awt.Dimension(70, 100));
        rangeTable.setMinimumSize(new java.awt.Dimension(70, 64));
        rangeTable.setPreferredSize(new java.awt.Dimension(70, 64));
        rangeTable.setRowMargin(5);
        rangeTable.setRowSelectionAllowed(false);
        jPanel3.add(rangeTable, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        logXbox.setText("Log Scale in X");
        logXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logXboxActionPerformed(evt);
            }
        });
        jPanel1.add(logXbox);

        logYbox.setText("Log Scale in Y");
        logYbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logYboxActionPerformed(evt);
            }
        });
        jPanel1.add(logYbox);

        jPanel3.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setBottomComponent(jPanel3);

        mainPane.setLeftComponent(jSplitPane1);

        figurePanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setText("Progress");
        jPanel4.add(jLabel2);

        processBar.setMaximum(system.getAlgorithm().getIterations());
        processBar.setValue(system.getTimer().getTimePoints().length);
        processBar.setMaximumSize(new java.awt.Dimension(300, 21));
        processBar.setPreferredSize(new java.awt.Dimension(160, 20));
        processBar.setStringPainted(true);
        jPanel4.add(processBar);

        figurePanel.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Resolution");
        jLabel1.setToolTipText("Maximum number of time points to be drawn");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel5.add(jLabel1);

        maxPointsSlider.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        maxPointsSlider.setMajorTickSpacing(system.getAlgorithm().getIterations() / 4);
        maxPointsSlider.setMaximum(system.getAlgorithm().getIterations());
        maxPointsSlider.setPaintLabels(true);
        maxPointsSlider.setPaintTicks(true);
        maxPointsSlider.setToolTipText("Maximum number of time points");
        maxPointsSlider.setValue(getMaxDataPoints());
        maxPointsSlider.setMaximumSize(new java.awt.Dimension(200, 32767));
        maxPointsSlider.setMinimumSize(new java.awt.Dimension(40, 40));
        maxPointsSlider.setName(""); // NOI18N
        maxPointsSlider.setPreferredSize(new java.awt.Dimension(200, 50));
        maxPointsSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxPointsSliderStateChanged(evt);
            }
        });
        jPanel5.add(maxPointsSlider);

        figurePanel.add(jPanel5, java.awt.BorderLayout.SOUTH);

        mainPane.setRightComponent(figurePanel);

        getContentPane().add(mainPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        saveSelectedDataItem.setText("Save Selected Data");
        saveSelectedDataItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSelectedDataItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveSelectedDataItem);

        closeItem.setText("Close");
        closeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeItemActionPerformed(evt);
            }
        });
        fileMenu.add(closeItem);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitItem);

        jMenuBar1.add(fileMenu);

        simMenu.setText("Simulation");

        startItem.setText("Start");
        startItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startItemActionPerformed(evt);
            }
        });
        simMenu.add(startItem);

        pauseItem.setText("Pause");
        pauseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseItemActionPerformed(evt);
            }
        });
        simMenu.add(pauseItem);

        resumeItem.setText("Resume");
        resumeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeItemActionPerformed(evt);
            }
        });
        simMenu.add(resumeItem);

        jMenuBar1.add(simMenu);

        viewMenu.setText("View");

        logXItem.setText("Log Scale in X axis");
        logXItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logXItemActionPerformed(evt);
            }
        });
        viewMenu.add(logXItem);

        logYItem.setText("Log Scale in Y axis");
        logYItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logYItemActionPerformed(evt);
            }
        });
        viewMenu.add(logYItem);

        selectAllItem.setText("Select All");
        selectAllItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllItemActionPerformed(evt);
            }
        });
        viewMenu.add(selectAllItem);

        autoUpdateBox.setSelected(true);
        autoUpdateBox.setText("Automated Updating");
        autoUpdateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoUpdateBoxActionPerformed(evt);
            }
        });
        viewMenu.add(autoUpdateBox);

        jMenuBar1.add(viewMenu);

        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

  private void resumeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeItemActionPerformed
        system.getAlgorithm().resume();
        autoUpdate();
  }//GEN-LAST:event_resumeItemActionPerformed

  private void pauseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseItemActionPerformed
       system.getAlgorithm().pause();
       autoUpdateThread.pause();
  }//GEN-LAST:event_pauseItemActionPerformed

  private void startItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startItemActionPerformed
        system.getAlgorithm().start();
        autoUpdate();
  }//GEN-LAST:event_startItemActionPerformed

  private void maxPointsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxPointsSliderStateChanged
        setMaxDataPoints( maxPointsSlider.getValue());
  }//GEN-LAST:event_maxPointsSliderStateChanged

  private void autoUpdateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoUpdateBoxActionPerformed
        autoUpdate();
  }//GEN-LAST:event_autoUpdateBoxActionPerformed

  private void logYboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logYboxActionPerformed
      boolean state = logYbox.isSelected();
      logYItem.setSelected(state);
      figure.setLogY(state);
      figure.repaint();
  }//GEN-LAST:event_logYboxActionPerformed

  private void logXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logXboxActionPerformed
      boolean state = logXbox.isSelected();
      logXItem.setSelected(state);
      figure.setLogX(state);
      figure.repaint();
  }//GEN-LAST:event_logXboxActionPerformed

  private void selectAllItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllItemActionPerformed
      int [] allIndices = new int [substanceNames.size()];
      for (int i = 0; i < allIndices.length; i++) allIndices[i] = i;
      substanceList.setSelectedIndices(allIndices);
  }//GEN-LAST:event_selectAllItemActionPerformed

  //
  // The following method is updated 4/19/2005 by LY
  // not quite working yet.
  //
  private void saveSelectedDataItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSelectedDataItemActionPerformed
       String outDir =  DyneticaProperties.getProperty("outputDirectory");
       JFileChooser fileChooser = new JFileChooser(outDir);
        int returnVal = fileChooser.showSaveDialog (this);
	if (returnVal == JFileChooser.APPROVE_OPTION) {
            File output = fileChooser.getSelectedFile();
             outDir = output.getParentFile().getAbsolutePath();
            //
            System.out.println(outDir);
            //
             dynetica.util.DyneticaProperties.setProperty("outputDirectory", outDir);
            if (fileChooser.getFileFilter().equals(fileChooser.getAcceptAllFileFilter()))
                    figure.saveData(output);
	}

  }//GEN-LAST:event_saveSelectedDataItemActionPerformed

  private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
  }//GEN-LAST:event_exitItemActionPerformed

  private void closeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeItemActionPerformed
        this.dispose();
  }//GEN-LAST:event_closeItemActionPerformed

  private void logXItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logXItemActionPerformed
        figure.setLogX(logXItem.getState());
        logXbox.setSelected(logXItem.getState());
  }//GEN-LAST:event_logXItemActionPerformed

  private void logYItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logYItemActionPerformed
        figure.setLogY(logYItem.getState());
  }//GEN-LAST:event_logYItemActionPerformed

  private void substanceListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_substanceListValueChanged
        updateFigure();
  }//GEN-LAST:event_substanceListValueChanged

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        autoUpdateThread = null;
        this.dispose();
    }//GEN-LAST:event_exitForm

    public void autoUpdate() {
      if (autoUpdateBox.getState()) {
         autoUpdateThread.start();
      }
      else {
           autoUpdateThread.pause();
      }
      
    }
    
    /** Getter for property maxDataPoints.
     * @return Value of property maxDataPoints.
 */
    public int getMaxDataPoints() {
        return maxDataPoints;
    }    
    
    /** Setter for property maxDataPoints.
     * @param maxDataPoints New value of property maxDataPoints.
 */
    public void setMaxDataPoints(int maxDataPoints) {
        this.maxDataPoints = Math.max(maxDataPoints, 1);
        updateFigure();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem autoUpdateBox;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JPanel figurePanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JCheckBoxMenuItem logXItem;
    private javax.swing.JCheckBox logXbox;
    private javax.swing.JCheckBoxMenuItem logYItem;
    private javax.swing.JCheckBox logYbox;
    private javax.swing.JSplitPane mainPane;
    private javax.swing.JSlider maxPointsSlider;
    private javax.swing.JMenuItem pauseItem;
    private javax.swing.JProgressBar processBar;
    private javax.swing.JTable rangeTable;
    private javax.swing.JMenuItem resumeItem;
    private javax.swing.JMenuItem saveSelectedDataItem;
    private javax.swing.JMenuItem selectAllItem;
    private javax.swing.JMenu simMenu;
    private javax.swing.JMenuItem startItem;
    private javax.swing.JList substanceList;
    private javax.swing.JLabel substanceListLabel;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables

    /** Holds value of property maxDataPoints. */
    private int maxDataPoints = 100;    

    
    class AutoUpdateThread extends Thread {
        Thread controlThread = null;
        
        public void run() {
            dynetica.algorithm.Algorithm algo = system.getAlgorithm();
            while (controlThread != null) {
              if (! algo.isFinished() && !algo.isInterrupted()) {
                    try {
                            updateFigure();
                            sleep(100);
                        }
                    catch (Exception e) {
                        break;
                    }
              }
              else if (algo.isFinished()) {
                    updateFigure();
                    break;
              };
            }
            //
            // stop the thread at the end of run
            //
            controlThread = null;
        }
        
        public void pause() {
            controlThread = null;
        }
        
        public void start() {
            if (controlThread == null) {
                controlThread = new Thread(this);
                controlThread.start();
            }
        }
    }
    
      class FigureAxisModel extends javax.swing.table.AbstractTableModel {      
       final Object[][] data = {
            {"xmin",  new Double (figure.getXmin())},
            {"xmax", new Double (figure.getXmax())},
            {"ymin", new Double (figure.getYmin())},
            {"ymax", new Double (figure.getYmax()) }
            }; 
            
       public FigureAxisModel() {
       }
       
       public void setFigure() {
           data[0][1] = new Double(figure.getXmin());
           data[1][1] = new Double(figure.getXmax());
           data[2][1] = new Double(figure.getYmin());
           data[3][1] = new Double(figure.getYmax());
           
           for (int i = 0; i < 4; i++) fireTableCellUpdated(i, 1);
       }
       
       public int getColumnCount() { return data[0].length;}
       public String getColumnName(int c) { return null;}
       public int getRowCount() { return data.length;}
       public Object getValueAt(int row, int col) {
            return data[row][col];
       }
        
       public Class getColumnClass(int c) {
             return getValueAt(0, c).getClass();
       }
        
        public boolean isCellEditable(int row, int col) {
            return (col == 1);
        }
        
        public void setValueAt(Object value, int row, int col) {
            data[row][col] = value;
            fireTableCellUpdated(row, col);
            
            double newValue = ((Double) value).doubleValue();
            if (row == 0) {
                figure.setXmin(newValue);
             }
            
            else if (row == 1) {
                figure.setXmax(newValue);
            }
            
            else if (row == 2) {
                figure.setYmin(newValue);
            }
            
            else if (row == 3) {
                figure.setYmax(newValue);
            }
            
        }    
  }

}
