/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dynetica.gui.plotting;

import dynetica.algorithm.HillEquationFit;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author chrismurphy
 */
public class HillEquationFitWindow extends javax.swing.JFrame {
    
    InteractiveFigure figure = new InteractiveFigure();
    HillEquationFit model;
    /**
     * Creates new form HillEquationFitWindow
     */
    public HillEquationFitWindow(HillEquationFit fit) {
        super("Hill Equation Fit");
        this.setMinimumSize(new Dimension(600,500));
        model = fit;
        
        String[] labels = new String[2];
        labels[0] = "Original Rate data for "+ model.getDependent().getName();
        labels[1] = "Best Fit Hill Equation";
        double[][] data = new double[2][model.getBestFitLine().length];
        data[0] = model.getDependent().getRates();
        data[1] = model.getBestFitLine();
        
        initComponents();
        figurePanel.add(figure.getPlotPanel(), java.awt.BorderLayout.CENTER);
        figure.plotData(model.getIndependent().getName(), labels,
            model.getIndependent().getValues(), data);
        figurePanel.setBorder(BorderFactory.createLineBorder(Color.black));
        figurePanel.repaint();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        figurePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        figurePanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(figurePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel figurePanel;
    // End of variables declaration//GEN-END:variables
}
