/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dynetica.gui.algorithms;

import dynetica.algorithm.*;
import dynetica.entity.*;
import dynetica.system.*;
import java.util.*;
import javax.swing.*;

/**
 * 
 * @author Derek Eidum (2013)
 */
public class BottleNeckEditor extends javax.swing.JPanel {
    BottleNeckSimulation bns;
    ReactiveSystem system;
    List<Substance> substances;
    DefaultComboBoxModel cheaterChoiceList = new DefaultComboBoxModel();
    DefaultComboBoxModel cooperatorChoiceList = new DefaultComboBoxModel();

    /**
     * Creates new form BottleNeckEditor
     */
    public BottleNeckEditor(ReactiveSystem sys) {
        system = sys;
        substances = sys.getSubstances();
        initComponents();
        setupLists();
    }

    private void setupLists() {
        for (Substance s : substances) {
            cheaterChoiceList.addElement(s.getName());
            cooperatorChoiceList.addElement(s.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cooperatorChoiceBox = new javax.swing.JComboBox();
        cheaterChoiceBox = new javax.swing.JComboBox();
        populationField = new javax.swing.JTextField();
        runButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        plotButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fractionField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        fixedMeanChoice = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        roundsField = new javax.swing.JTextField();
        saveCheckBox = new javax.swing.JCheckBox();
        normalizeCheckBox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        initialValField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cooperator Species");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24,
                -1, -1));

        jLabel2.setText("Cheater Species");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55,
                -1, -1));

        jLabel3.setText("Population Size");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86,
                -1, -1));

        cooperatorChoiceBox.setModel(cooperatorChoiceList);
        add(cooperatorChoiceBox,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 141,
                        -1));

        cheaterChoiceBox.setModel(cheaterChoiceList);
        add(cheaterChoiceBox,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 141,
                        -1));

        populationField.setText("5");
        add(populationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                280, 80, 67, -1));

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });
        add(runButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20,
                260, -1, -1));

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(136,
                260, -1, -1));

        plotButton.setText("Plot");
        plotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotButtonActionPerformed(evt);
            }
        });
        add(plotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(246,
                260, -1, -1));

        jLabel4.setText("Initial Cheater Fraction");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116,
                -1, -1));

        fractionField.setText("0.1");
        add(fractionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                210, 110, 141, -1));

        jLabel5.setText("Simulation Time");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142,
                -1, -1));

        timeField.setText("100");
        add(timeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210,
                140, 141, -1));

        fixedMeanChoice.setModel(new javax.swing.DefaultComboBoxModel(
                new String[] { "Fixed", "Mean" }));
        add(fixedMeanChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                210, 80, 64, -1));

        jLabel6.setText("Number of Bottleneck Rounds");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168,
                -1, -1));

        roundsField.setText("5");
        add(roundsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210,
                170, 141, -1));

        saveCheckBox.setText("Save All Simulation Data");
        saveCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCheckBoxActionPerformed(evt);
            }
        });
        add(saveCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20,
                192, -1, -1));

        normalizeCheckBox.setText("Normalize Initial Values");
        normalizeCheckBox
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        normalizeCheckBoxActionPerformed(evt);
                    }
                });
        add(normalizeCheckBox,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 219, -1,
                        -1));

        jLabel9.setText("Value:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210,
                220, -1, -1));

        initialValField.setText("1.0");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings
                .createAutoBinding(
                        org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                        normalizeCheckBox, org.jdesktop.beansbinding.ELProperty
                                .create("${selected}"), initialValField,
                        org.jdesktop.beansbinding.BeanProperty
                                .create("editable"));
        bindingGroup.addBinding(binding);

        add(initialValField, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                250, 220, 100, -1));

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_runButtonActionPerformed
        Substance cheater = system.getSubstance((String) cheaterChoiceBox
                .getSelectedItem());
        Substance cooperator = system.getSubstance((String) cooperatorChoiceBox
                .getSelectedItem());
        int subpopSize = (int) Double.parseDouble(populationField.getText());
        int rounds = (int) Double.parseDouble(roundsField.getText());
        double initFrac = Double.parseDouble(fractionField.getText());
        double simTime = Double.parseDouble(timeField.getText());
        bns = new BottleNeckSimulation(system, cooperator, cheater, subpopSize,
                initFrac, simTime, rounds);
        if (((String) fixedMeanChoice.getSelectedItem())
                .equalsIgnoreCase("Mean")) {
            bns.setPoisson(true);
        }
        bns.setSave(saveCheckBox.isSelected());
        if (normalizeCheckBox.isSelected()) {
            bns.setNormalize(true);
            bns.setNormalizedIV(Double.parseDouble(initialValField.getText()));
        }
        bns.start();
    }// GEN-LAST:event_runButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pauseButtonActionPerformed
        if (bns != null) {
            bns.pause();
        }
    }// GEN-LAST:event_pauseButtonActionPerformed

    private void plotButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plotButtonActionPerformed
        JFrame jf = new dynetica.gui.plotting.PhasePlaneWindow(system);
        jf.setVisible(true);
    }// GEN-LAST:event_plotButtonActionPerformed

    private void saveCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveCheckBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_saveCheckBoxActionPerformed

    private void normalizeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_normalizeCheckBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_normalizeCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cheaterChoiceBox;
    private javax.swing.JComboBox cooperatorChoiceBox;
    private javax.swing.JComboBox fixedMeanChoice;
    private javax.swing.JTextField fractionField;
    private javax.swing.JTextField initialValField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox normalizeCheckBox;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton plotButton;
    private javax.swing.JTextField populationField;
    private javax.swing.JTextField roundsField;
    private javax.swing.JButton runButton;
    private javax.swing.JCheckBox saveCheckBox;
    private javax.swing.JTextField timeField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
