/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dynetica.gui.algorithms;

import dynetica.algorithm.HillEquationFit;
import dynetica.entity.Substance;
import dynetica.gui.plotting.HillEquationFitWindow;
import dynetica.system.ReactiveSystem;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author chrismurphy
 */
public class HillEquationFitEditor extends javax.swing.JPanel {

    final HillEquationFit model;
    final ReactiveSystem system;
    
    DefaultComboBoxModel substanceBoxModel = new DefaultComboBoxModel();
    DefaultComboBoxModel productBoxModel = new DefaultComboBoxModel();
    
    /**
     * Creates new form HillEquationFitEditor
     */
    public HillEquationFitEditor(HillEquationFit fitmodel, ReactiveSystem sys) {
        model = fitmodel;
        system = sys;
        
        List substances = system.getSubstances();
        int nSubs = substances.size(); // substances.length;
        Substance s;
        substanceBoxModel.addElement("");
        productBoxModel.addElement("");
        for (int i = 0; i < nSubs; i++) {
            s = (Substance) (substances.get(i));
            substanceBoxModel.addElement(s.getName());
            productBoxModel.addElement("Rate of " + s.getName());
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        substanceLabel = new javax.swing.JLabel();
        substanceComboBox = new javax.swing.JComboBox();
        runButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        productLabel = new javax.swing.JLabel();
        productComboBox = new javax.swing.JComboBox();
        maxRateLabel = new javax.swing.JLabel();
        maxRateField = new javax.swing.JTextField();

        substanceLabel.setText("Choose Substance:");

        substanceComboBox.setModel(substanceBoxModel);
        substanceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substanceComboBoxActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        productLabel.setText("Choose Product Rate:");

        productComboBox.setModel(productBoxModel);
        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        maxRateLabel.setText("Max Product Rate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(runButton)
                            .addComponent(substanceLabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(substanceComboBox, 0, 136, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(closeButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productLabel)
                        .addGap(18, 18, 18)
                        .addComponent(productComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maxRateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxRateField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substanceLabel)
                    .addComponent(substanceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productLabel)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxRateLabel)
                    .addComponent(maxRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // TODO add your handling code here:
        if(model.getIndependent() == null || model.getDependent() == null){
                        JOptionPane.showMessageDialog(this.getRootPane().getParent(), "Please choose substance and product");
        }
        model.setMaxRate(Double.parseDouble(maxRateField.getText()));
        model.run();
        JOptionPane.showMessageDialog(this.getRootPane().getParent(), "Km = " + model.getKm() + "\nn = " + model.getHillCoefficient());
        model.createBestFitLine();
        HillEquationFitWindow frame = new HillEquationFitWindow(model);
        frame.pack();
        frame.show();
    }//GEN-LAST:event_runButtonActionPerformed

    private void substanceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substanceComboBoxActionPerformed
        // TODO add your handling code here:
        if(substanceBoxModel.getSelectedItem()=="")
            return;
        model.setIndependent(system.getSubstance((String) substanceBoxModel.getSelectedItem()));
    }//GEN-LAST:event_substanceComboBoxActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
        if(productBoxModel.getSelectedItem()=="")
            return;
        model.setDependent(system.getSubstance(((String) productBoxModel.getSelectedItem()).substring(8)));
    }//GEN-LAST:event_productComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField maxRateField;
    private javax.swing.JLabel maxRateLabel;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JLabel productLabel;
    private javax.swing.JButton runButton;
    private javax.swing.JComboBox substanceComboBox;
    private javax.swing.JLabel substanceLabel;
    // End of variables declaration//GEN-END:variables
}
