/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dynetica.gui.algorithms;

import dynetica.algorithm.*;
import dynetica.entity.*;
import dynetica.expression.*;
import dynetica.objective.AbstractMetric;
import dynetica.system.ReactiveSystem;
import dynetica.util.Numerics;
import java.util.*;
import javax.swing.*;

/**
 * 
 * @author Derek Eidum (2013)
 */
public class ParameterSearchDoseResponseEditor extends javax.swing.JPanel {
    DefaultListModel allParametersListModel = new DefaultListModel();
    DefaultListModel searchParametersListModel = new DefaultListModel();
    DefaultListModel objectivesListModel = new DefaultListModel();
    DefaultComboBoxModel variableSelectorModel = new DefaultComboBoxModel();

    ArrayList<TargetDoseObjective> objectivesList = new ArrayList<TargetDoseObjective>();

    ReactiveSystem system;
    ParameterSearchDoseResponse psdr = null;

    // Parameters for the search and analysis algorithms
    Variable variable;
    double min;
    double max;
    int numPoints;
    double time;
    boolean logScale;

    /**
     * Creates new form ParameterSearchDoseResponseEditor
     */
    public ParameterSearchDoseResponseEditor(ReactiveSystem sys) {
        system = sys;
        initComponents();
        setUpLists();
    }

    private void setUpLists() {
        List substances = system.getSubstances();
        List parameters = system.getParameters();
        for (int i = 0; i < substances.size(); i++) {
            Substance s = (Substance) substances.get(i);
            if (s instanceof ExpressionVariable) {
                continue;
            }
            variableSelectorModel.addElement(s.getName());
        }
        for (int i = 0; i < parameters.size(); i++) {
            Parameter p = (Parameter) parameters.get(i);
            if (p.getName().equals("Time")) {
                continue;
            }
            variableSelectorModel.addElement(p.getName());
            allParametersListModel.addElement(p.getName());
        }
    }

    public void addObjective(TargetDoseObjective tdo) {
        objectivesList.add(tdo);
        objectivesListModel.addElement(tdo.toString());
    }

    public void normalizeObjectiveWeights() {
        double sum = 0;
        for (TargetDoseObjective tdo : objectivesList) {
            sum += tdo.getWeight();
        }
        if (sum == 1) {
            return;
        }
        for (TargetDoseObjective tdo : objectivesList) {
            tdo.setWeight(tdo.getWeight() / sum);
        }
        System.out.println("Normalizing objective weights...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        variableSelector = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numPointsField = new javax.swing.JTextField();
        minField = new javax.swing.JTextField();
        maxField = new javax.swing.JTextField();
        logScaleCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        populationSizeField = new javax.swing.JTextField();
        numGenerationsField = new javax.swing.JTextField();
        timeField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        allParametersListBox = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchParametersListBox = new javax.swing.JList();
        addParametersButton = new javax.swing.JButton();
        removeParametersButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        objectivesListBox = new javax.swing.JList();
        addObjectiveButton = new javax.swing.JButton();
        editObjectiveButton = new javax.swing.JButton();
        removeObjectiveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        randomizeCheckBox = new javax.swing.JCheckBox();
        runButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        resetParametersButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        thresholdField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        plotButton = new javax.swing.JButton();

        jLabel1.setText("Variable");

        variableSelector.setModel(variableSelectorModel);
        variableSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableSelectorActionPerformed(evt);
            }
        });

        jLabel2.setText("Min");

        jLabel3.setText("Max");

        jLabel4.setText("Number of Points");

        numPointsField.setText("20");
        numPointsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPointsFieldActionPerformed(evt);
            }
        });

        minField.setText("0");

        maxField.setText("1");

        logScaleCheckBox.setText("Log Scale");

        jLabel5.setText("Vector Population Size");

        jLabel6.setText("Number of Generations");

        jLabel7.setText("Simulation Time");

        populationSizeField.setText("10");

        numGenerationsField.setText("50");

        timeField.setText("100");
        timeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFieldActionPerformed(evt);
            }
        });

        allParametersListBox.setModel(allParametersListModel);
        jScrollPane1.setViewportView(allParametersListBox);

        jLabel8.setText("Search Parameters");

        searchParametersListBox.setModel(searchParametersListModel);
        jScrollPane2.setViewportView(searchParametersListBox);

        addParametersButton.setText("Add");
        addParametersButton
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        addParametersButtonActionPerformed(evt);
                    }
                });

        removeParametersButton.setText("Remove");
        removeParametersButton
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        removeParametersButtonActionPerformed(evt);
                    }
                });

        objectivesListBox.setModel(objectivesListModel);
        jScrollPane3.setViewportView(objectivesListBox);

        addObjectiveButton.setText("Add");
        addObjectiveButton
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        addObjectiveButtonActionPerformed(evt);
                    }
                });

        editObjectiveButton.setText("Edit");
        editObjectiveButton
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        editObjectiveButtonActionPerformed(evt);
                    }
                });

        removeObjectiveButton.setText("Remove");
        removeObjectiveButton.setMaximumSize(new java.awt.Dimension(75, 23));
        removeObjectiveButton.setMinimumSize(new java.awt.Dimension(75, 23));
        removeObjectiveButton.setPreferredSize(new java.awt.Dimension(75, 23));
        removeObjectiveButton
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        removeObjectiveButtonActionPerformed(evt);
                    }
                });

        jLabel9.setText("Target Objectives");

        randomizeCheckBox.setText("Randomize Initial Population");

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        resetParametersButton.setText("Reset Parameters");
        resetParametersButton
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        resetParametersButtonActionPerformed(evt);
                    }
                });

        jLabel10.setText("Threshold");

        thresholdField.setText("0.05");

        plotButton.setText("Plot Response");
        plotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(
                                                                        runButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(
                                                                        stopButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jLabel1)
                                                                .addGap(42, 42,
                                                                        42)
                                                                .addComponent(
                                                                        variableSelector,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        190,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jLabel2)
                                                                .addGap(58, 58,
                                                                        58)
                                                                .addComponent(
                                                                        minField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(32, 32,
                                                                        32)
                                                                .addComponent(
                                                                        jLabel4)
                                                                .addGap(4, 4, 4)
                                                                .addComponent(
                                                                        numPointsField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        38,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jLabel3)
                                                                .addGap(54, 54,
                                                                        54)
                                                                .addComponent(
                                                                        maxField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(32, 32,
                                                                        32)
                                                                .addComponent(
                                                                        logScaleCheckBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        124,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jSeparator1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        270,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jLabel5)
                                                                .addGap(33, 33,
                                                                        33)
                                                                .addComponent(
                                                                        populationSizeField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        131,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jLabel6)
                                                                .addGap(28, 28,
                                                                        28)
                                                                .addComponent(
                                                                        numGenerationsField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        131,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        randomizeCheckBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        270,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(100,
                                                                        100,
                                                                        100)
                                                                .addComponent(
                                                                        jLabel8))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        132,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jScrollPane2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        128,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(42, 42,
                                                                        42)
                                                                .addComponent(
                                                                        addParametersButton)
                                                                .addGap(82, 82,
                                                                        82)
                                                                .addComponent(
                                                                        removeParametersButton))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jSeparator2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        270,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(101,
                                                                        101,
                                                                        101)
                                                                .addComponent(
                                                                        jLabel9))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        jScrollPane3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        270,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10,
                                                                        10)
                                                                .addComponent(
                                                                        addObjectiveButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        75,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(23, 23,
                                                                        23)
                                                                .addComponent(
                                                                        editObjectiveButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        75,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18,
                                                                        18)
                                                                .addComponent(
                                                                        removeObjectiveButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        79,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGap(10,
                                                                                                        10,
                                                                                                        10)
                                                                                                .addComponent(
                                                                                                        jLabel7))
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(
                                                                                                        jLabel10)))
                                                                .addGap(66, 66,
                                                                        66)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(
                                                                                        timeField)
                                                                                .addComponent(
                                                                                        thresholdField,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        131,
                                                                                        Short.MAX_VALUE))))
                                .addGap(0, 10, Short.MAX_VALUE))
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator3)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        plotButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(
                                                                        resetParametersButton)))
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addComponent(
                                                                        jLabel1))
                                                .addComponent(
                                                        variableSelector,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        minField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(
                                                        numPointsField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        jLabel2)
                                                                                .addComponent(
                                                                                        jLabel4))))
                                .addGap(10, 10, 10)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(4, 4, 4)
                                                                .addComponent(
                                                                        jLabel3))
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(
                                                                        maxField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(logScaleCheckBox))
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addComponent(
                                                                        jLabel5))
                                                .addComponent(
                                                        populationSizeField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addComponent(
                                                                        jLabel6))
                                                .addComponent(
                                                        numGenerationsField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addComponent(
                                                                        jLabel7))
                                                .addComponent(
                                                        timeField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(
                                                        thresholdField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(randomizeCheckBox)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel8)
                                .addGap(4, 4, 4)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        jScrollPane1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        70,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(
                                                        jScrollPane2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        70,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        addParametersButton)
                                                .addComponent(
                                                        removeParametersButton))
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9)
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        82,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        addObjectiveButton)
                                                .addComponent(
                                                        editObjectiveButton)
                                                .addComponent(
                                                        removeObjectiveButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(runButton)
                                                .addComponent(stopButton))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(
                                                        resetParametersButton)
                                                .addComponent(plotButton))));
    }// </editor-fold>//GEN-END:initComponents

    private void numPointsFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numPointsFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_numPointsFieldActionPerformed

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_timeFieldActionPerformed

    private void addParametersButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addParametersButtonActionPerformed
        Object[] selectedNames = allParametersListBox.getSelectedValues();
        for (int i = 0; i < selectedNames.length; i++) {
            if (!searchParametersListModel.contains(selectedNames[i]))
                searchParametersListModel.addElement(selectedNames[i]);
        }
    }// GEN-LAST:event_addParametersButtonActionPerformed

    private void removeParametersButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removeParametersButtonActionPerformed
        Object[] selectedNames = searchParametersListBox.getSelectedValues();
        for (int i = 0; i < selectedNames.length; i++) {
            searchParametersListModel.removeElement(selectedNames[i]);
        }
    }// GEN-LAST:event_removeParametersButtonActionPerformed

    private void resetParametersButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetParametersButtonActionPerformed
        Object[] parameters = system.getParameters().toArray();
        for (int i = 0; i < parameters.length; i++) {
            Parameter p = (Parameter) parameters[i];
            p.resetSearchingValue();
        }
    }// GEN-LAST:event_resetParametersButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_runButtonActionPerformed
        normalizeObjectiveWeights();
        String variableName = (String) variableSelector.getSelectedItem();
        variable = (Variable) system.getEntity(variableName);
        if (variable == null) {
            System.out.println("WHY!?!?!?");
            return;
        }
        min = Double.parseDouble(minField.getText());
        max = Double.parseDouble(maxField.getText());
        numPoints = Integer.parseInt(numPointsField.getText());
        logScale = logScaleCheckBox.isSelected();
        double[] xValues;
        if (logScale) {
            xValues = Numerics.logspace(min, max, numPoints);
        } else {
            xValues = Numerics.linspace(min, max, numPoints);
        }
        int popSize = Integer.parseInt(populationSizeField.getText());
        int generations = Integer.parseInt(numGenerationsField.getText());
        double threshold = Double.parseDouble(thresholdField.getText());
        time = Double.parseDouble(timeField.getText());
        boolean randomize = randomizeCheckBox.isSelected();
        Parameter[] parameterList = new Parameter[searchParametersListModel
                .size()];
        for (int i = 0; i < parameterList.length; i++) {
            parameterList[i] = (Parameter) system
                    .getParameter((String) searchParametersListModel.get(i));
        }

        psdr = new ParameterSearchDoseResponse(system, parameterList,
                objectivesList, variable, xValues, time, threshold,
                generations, popSize, randomize);
        psdr.start();
    }// GEN-LAST:event_runButtonActionPerformed

    private void addObjectiveButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addObjectiveButtonActionPerformed
        JFrame jf = new JFrame("Dose Response Objective Editor");
        jf.getContentPane().add(new DoseObjectiveEditor(jf, this));
        jf.pack();
        jf.show();
    }// GEN-LAST:event_addObjectiveButtonActionPerformed

    private void editObjectiveButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editObjectiveButtonActionPerformed
        String id = (String) objectivesListBox.getSelectedValue();
        objectivesListModel.removeElement(id);
        for (int i = 0; i < objectivesList.size(); i++) {
            TargetDoseObjective tdo = objectivesList.get(i);
            if (tdo.toString().equalsIgnoreCase(id)) {
                JFrame jf = new JFrame("Dose Response Objective Editor");
                jf.getContentPane().add(new DoseObjectiveEditor(jf, this, tdo));
                jf.pack();
                jf.show();
                objectivesList.remove(tdo);
                break;
            }
        }

    }// GEN-LAST:event_editObjectiveButtonActionPerformed

    private void removeObjectiveButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removeObjectiveButtonActionPerformed
        String id = (String) objectivesListBox.getSelectedValue();
        objectivesListModel.removeElement(id);
        for (int i = 0; i < objectivesList.size(); i++) {
            TargetDoseObjective tdo = objectivesList.get(i);
            if (tdo.toString().equalsIgnoreCase(id)) {
                objectivesList.remove(tdo);
                break;
            }
        }
    }// GEN-LAST:event_removeObjectiveButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_stopButtonActionPerformed
        if (psdr != null) {
            psdr.pause();
        }
    }// GEN-LAST:event_stopButtonActionPerformed

    private void variableSelectorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_variableSelectorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_variableSelectorActionPerformed

    private void plotButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plotButtonActionPerformed
        if (psdr == null) {
            return;
        }
        if (psdr.getSimulationThread() != null) {
            return;
        }
        ArrayList<TargetDoseObjective> tdoList = psdr.getObjectives();
        ArrayList<AbstractMetric> metricList = new ArrayList<AbstractMetric>();
        for (TargetDoseObjective tdo : tdoList) {
            metricList.add(tdo.getMetric());
        }
        SensitivityAnalysis sa = new SensitivityAnalysis(variable, metricList,
                system, min, max, numPoints, time, logScale);
        sa.setPlotOnComplete(true);
        sa.start();
        System.out.println("Analysis complete.");
    }// GEN-LAST:event_plotButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObjectiveButton;
    private javax.swing.JButton addParametersButton;
    private javax.swing.JList allParametersListBox;
    private javax.swing.JButton editObjectiveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox logScaleCheckBox;
    private javax.swing.JTextField maxField;
    private javax.swing.JTextField minField;
    private javax.swing.JTextField numGenerationsField;
    private javax.swing.JTextField numPointsField;
    private javax.swing.JList objectivesListBox;
    private javax.swing.JButton plotButton;
    private javax.swing.JTextField populationSizeField;
    private javax.swing.JCheckBox randomizeCheckBox;
    private javax.swing.JButton removeObjectiveButton;
    private javax.swing.JButton removeParametersButton;
    private javax.swing.JButton resetParametersButton;
    private javax.swing.JButton runButton;
    private javax.swing.JList searchParametersListBox;
    private javax.swing.JButton stopButton;
    private javax.swing.JTextField thresholdField;
    private javax.swing.JTextField timeField;
    private javax.swing.JComboBox variableSelector;
    // End of variables declaration//GEN-END:variables
}
