/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dynetica.gui.algorithms;

import dynetica.gui.algorithms.TargetObjectiveEditor;
import dynetica.algorithm.*;
import dynetica.entity.*;
import dynetica.system.*;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author Derek Eidum (2013)
 */
public class ParameterSearchGeneticEditor extends javax.swing.JPanel{

    
    ParameterSearchGenetic parameterSearch;
    ReactiveSystem system;
    DefaultListModel searchParameters = new DefaultListModel();
    DefaultListModel fixedParameters = new DefaultListModel();
    DefaultListModel targetObjectives = new DefaultListModel(); 
    ArrayList<TargetObjective> targetList = new ArrayList<TargetObjective>();
    
    /**
     * Creates new form ParameterSearchMonteCarloEditor
     */
    public ParameterSearchGeneticEditor(ReactiveSystem sys) {
        system = sys;
        setupLists();
        initComponents();
    }
    
    private void setupLists() {
        List parameters = system.getParameters();
        for (int i=0; i<parameters.size(); i++) {
            Parameter p = (Parameter) parameters.get(i);
            if (p.getName().equals("Time")) {continue;}
            fixedParameters.addElement(p.getName());
        }
    }
    
    public void addTargetObjective(TargetObjective to) {
        targetList.add(to);
        targetObjectives.addElement(to.getSubstance().getName());
    }
    
    public void normalizeObjectiveWeights() {
        double sum = 0;
        for (TargetObjective to : targetList) {
            sum += to.getWeight();
        }
        if (sum == 1) {return;}
        for (TargetObjective to : targetList) {
            to.setWeight(to.getWeight() / sum);
        }
        System.out.println("Normalizing objective weights...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeField = new javax.swing.JFormattedTextField();
        thresholdField = new javax.swing.JFormattedTextField();
        generationsField = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchParameterList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        fixedList = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        pauseButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        targetListBox = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        addObjectiveButton = new javax.swing.JButton();
        removeObjectiveButton = new javax.swing.JButton();
        editObjectiveButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        populationField = new javax.swing.JTextField();
        randomizeCheckBox = new javax.swing.JCheckBox();

        jLabel3.setText("Simulation Time");

        jLabel4.setText("Threshold");

        jLabel5.setText("Max Generations");

        timeField.setText("100");

        thresholdField.setText("0.05");
        thresholdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdFieldActionPerformed(evt);
            }
        });

        generationsField.setText("50");
        generationsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generationsFieldActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        searchParameterList.setModel(searchParameters);
        jScrollPane2.setViewportView(searchParameterList);

        fixedList.setModel(fixedParameters);
        jScrollPane1.setViewportView(fixedList);

        jLabel1.setText("Parameters");

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset Parameters");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton)
                        .addGap(48, 48, 48)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(runButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton)
                        .addGap(71, 71, 71))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton)
                    .addComponent(pauseButton)
                    .addComponent(resetButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        targetListBox.setModel(targetObjectives);
        jScrollPane3.setViewportView(targetListBox);

        jLabel6.setText("Target Objectives");

        addObjectiveButton.setText("Add");
        addObjectiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObjectiveButtonActionPerformed(evt);
            }
        });

        removeObjectiveButton.setText("Remove");
        removeObjectiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeObjectiveButtonActionPerformed(evt);
            }
        });

        editObjectiveButton.setText("Edit");
        editObjectiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editObjectiveButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Population Size");

        populationField.setText("20");
        populationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populationFieldActionPerformed(evt);
            }
        });

        randomizeCheckBox.setText("Randomize Initial Population");
        randomizeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomizeCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(thresholdField)
                                    .addComponent(generationsField)
                                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(populationField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(randomizeCheckBox)
                .addGap(18, 18, 18)
                .addComponent(addObjectiveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeObjectiveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editObjectiveButton)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeObjectiveButton)
                            .addComponent(addObjectiveButton)
                            .addComponent(editObjectiveButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(thresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(generationsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(populationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomizeCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       Object[] selectedNames = fixedList.getSelectedValues();
       for (int i = 0; i < selectedNames.length; i++) {
           if (! searchParameters.contains(selectedNames[i]))
           searchParameters.addElement(selectedNames[i]);
       }
    }//GEN-LAST:event_addButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        parameterSearch.pause();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        normalizeObjectiveWeights();
        Parameter [] parameterList = new Parameter[searchParameters.size()];
        for (int i = 0; i < parameterList.length; i++) {
            parameterList[i] = (Parameter) system.getParameter((String) searchParameters.get(i));
            //System.out.println(i + ": " + searchParameters.get(i) + " ; " + parameterList[i].getValue());
        }
        double time = Double.parseDouble(timeField.getText());
        double threshold = Double.parseDouble(thresholdField.getText());
        int numGens = (int) Double.parseDouble(generationsField.getText());
        int popSize = (int) Double.parseDouble(populationField.getText());
        parameterSearch = new ParameterSearchGenetic(system, parameterList,targetList, 
                time, threshold, numGens, popSize, randomizeCheckBox.isSelected());     
        parameterSearch.start();
    }//GEN-LAST:event_runButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
      Object[] selectedNames = searchParameterList.getSelectedValues();
      for (int i = 0; i < selectedNames.length; i++) {
          searchParameters.removeElement(selectedNames[i]);
      }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        Object[] parameters = system.getParameters().toArray();
        for (int i = 0; i < parameters.length; i++){
            Parameter p = (Parameter) parameters[i];
            p.resetSearchingValue();
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void addObjectiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObjectiveButtonActionPerformed
        JFrame jf = new JFrame("New Objective Function");
        jf.getContentPane().add(new TargetObjectiveEditor(jf, this));
        jf.pack();
        jf.show();
    }//GEN-LAST:event_addObjectiveButtonActionPerformed

    private void removeObjectiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeObjectiveButtonActionPerformed
        removeSelectedObjective();
    }//GEN-LAST:event_removeObjectiveButtonActionPerformed

    private void editObjectiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editObjectiveButtonActionPerformed
        String name = (String) targetListBox.getSelectedValue();
        TargetObjective ts = null;
        for (TargetObjective obj : targetList) {
            if (obj.getSubstance().getName().equals(name)) {
                ts = obj;
                break;
            }
        }
        removeSelectedObjective();
        JFrame jf = new JFrame("Edit Objective Function");
        jf.getContentPane().add(new TargetObjectiveEditor(jf, this, ts));
        jf.pack();
        jf.show();
    }//GEN-LAST:event_editObjectiveButtonActionPerformed

    private void thresholdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thresholdFieldActionPerformed

    private void populationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_populationFieldActionPerformed

    private void generationsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generationsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generationsFieldActionPerformed

    private void randomizeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomizeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randomizeCheckBoxActionPerformed

    
    public void removeSelectedObjective() {
        Object selected = targetListBox.getSelectedValue();
        if (selected==null) {return;}
        String name = (String) selected;
        targetObjectives.removeElement(selected);
        for (TargetObjective to : targetList) {
            if (name.equals(to.getSubstance().getName())) {
                targetList.remove(to);
                break;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addObjectiveButton;
    private javax.swing.JButton editObjectiveButton;
    private javax.swing.JList fixedList;
    private javax.swing.JFormattedTextField generationsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton pauseButton;
    private javax.swing.JTextField populationField;
    private javax.swing.JCheckBox randomizeCheckBox;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeObjectiveButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton runButton;
    private javax.swing.JList searchParameterList;
    private javax.swing.JList targetListBox;
    private javax.swing.JFormattedTextField thresholdField;
    private javax.swing.JFormattedTextField timeField;
    // End of variables declaration//GEN-END:variables
}
