/*
 * RK4Editor.java
 *
 * Created on April 17, 2001, 12:10 AM
 */

package dynetica.gui.algorithms;

/**
 * 
 * @author Lingchong You
 * @version 0.01
 */
public class RK4Editor extends javax.swing.JPanel {

    /** Creates new customizer RK4Editor */
    dynetica.algorithm.RungeKutta4 algorithm;

    public RK4Editor(dynetica.algorithm.RungeKutta4 rk4) {
        this.algorithm = rk4;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        maxStepField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        samplingStepField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        iterationField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Runge-Kutta algorithm");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jLabel2.setText("Maximum timestep");
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(jLabel2);

        maxStepField.setText(String.valueOf(algorithm.getMaxStep()));
        maxStepField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        maxStepField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxStepFieldActionPerformed(evt);
            }
        });
        maxStepField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maxStepFieldFocusLost(evt);
            }
        });
        jPanel1.add(maxStepField);

        jLabel4.setText("Sampling timestep");
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(jLabel4);

        samplingStepField.setText(String.valueOf(algorithm.getSamplingStep()));
        samplingStepField
                .setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        samplingStepField
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        samplingStepFieldActionPerformed(evt);
                    }
                });
        samplingStepField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                samplingStepFieldFocusLost(evt);
            }
        });
        jPanel1.add(samplingStepField);

        jLabel6.setText("Number of iterations");
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(jLabel6);

        iterationField.setText(String.valueOf(algorithm.getIterations()));
        iterationField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        iterationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterationFieldActionPerformed(evt);
            }
        });
        iterationField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                iterationFieldFocusLost(evt);
            }
        });
        jPanel1.add(iterationField);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void iterationFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_iterationFieldFocusLost
        setIterations();
    }// GEN-LAST:event_iterationFieldFocusLost

    private void iterationFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_iterationFieldActionPerformed
        setIterations();
    }// GEN-LAST:event_iterationFieldActionPerformed

    private void samplingStepFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_samplingStepFieldFocusLost
        setSamplingStep();
    }// GEN-LAST:event_samplingStepFieldFocusLost

    private void samplingStepFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_samplingStepFieldActionPerformed
        setSamplingStep();
    }// GEN-LAST:event_samplingStepFieldActionPerformed

    private void maxStepFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_maxStepFieldFocusLost
        setMaxStep();
    }// GEN-LAST:event_maxStepFieldFocusLost

    private void maxStepFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maxStepFieldActionPerformed
        setMaxStep();
    }// GEN-LAST:event_maxStepFieldActionPerformed

    private void setMaxStep() {
        algorithm.setMaxStep(Double.parseDouble(maxStepField.getText()));
    }

    private void setSamplingStep() {
        algorithm.setSamplingStep(Double.parseDouble(samplingStepField
                .getText()));
    }

    private void setIterations() {
        algorithm.setIterations(Integer.parseInt(iterationField.getText()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iterationField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxStepField;
    private javax.swing.JTextField samplingStepField;
    // End of variables declaration//GEN-END:variables

}
