package dynetica.gui.algorithms;

import dynetica.gui.algorithms.MetricEditor;
import dynetica.algorithm.*;
import dynetica.entity.*;
import dynetica.objective.*;
import dynetica.system.*;
import java.util.*;
import javax.swing.*;

/**
 * 
 * @author Derek Eidum (2013)
 */
public class TargetObjectiveEditor extends javax.swing.JPanel {
    ParameterSearchGeneticEditor psg;
    ReactiveSystem system;
    AbstractMetric metric;
    AbstractObjective objective = null;
    JFrame parentFrame = null;

    /**
     * Creates new form TargetObjectiveEditor
     */
    public TargetObjectiveEditor(JFrame frame, ParameterSearchGeneticEditor p) {
        parentFrame = frame;
        psg = p;
        system = p.system;
        initComponents();
    }

    public TargetObjectiveEditor(JFrame frame, ParameterSearchGeneticEditor p,
            TargetObjective to) {
        parentFrame = frame;
        psg = p;
        system = p.system;
        initComponents();
        objective = to.getObjectiveFunction();
        weightField.setText((new Double(to.getWeight())).toString());
    }

    public void updateText() {
        if (metric != null) {
            metricField.setText(metric.toString());
        }
        if (objective == null) {
            return;
        }
        objective.setMetric(metric);
        objectiveTextField.setText(objective.toString());
    }

    public void setMetric(AbstractMetric m) {
        metric = m;
        if (objective != null) {
            objective.setMetric(m);
        }
        if (metric instanceof CorrelationCoefficient) {
            objective = new MatchSubstance(metric);
            objectiveChoice.setEditable(false);
        } else {
            objectiveChoice.setEditable(true);
        }
        updateText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        objectiveChoice = new javax.swing.JComboBox();
        objectiveTextField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        metricField = new javax.swing.JTextField();
        selectButton = new javax.swing.JButton();

        jLabel1.setText("Metric:");

        jLabel2.setText("Objective");

        jLabel3.setText("Weight");

        objectiveChoice.setModel(new javax.swing.DefaultComboBoxModel(
                new String[] { "Select Function...", "Target Value",
                        "Maximize", "Minimize" }));
        objectiveChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objectiveChoiceActionPerformed(evt);
            }
        });
        objectiveChoice
                .addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                    public void propertyChange(
                            java.beans.PropertyChangeEvent evt) {
                        objectiveChoicePropertyChange(evt);
                    }
                });

        objectiveTextField.setEnabled(false);

        weightField.setText("1");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        metricField.setEditable(false);
        metricField.setText("Select a metric...");

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        jLabel3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(
                                                                        weightField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        100,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(
                                                        objectiveTextField)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(
                                                                                        jLabel2)
                                                                                .addComponent(
                                                                                        jLabel1))
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGap(14,
                                                                                                        14,
                                                                                                        14)
                                                                                                .addGroup(
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        metricField)
                                                                                                                .addComponent(
                                                                                                                        objectiveChoice,
                                                                                                                        0,
                                                                                                                        167,
                                                                                                                        Short.MAX_VALUE)))
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGap(32,
                                                                                                        32,
                                                                                                        32)
                                                                                                .addComponent(
                                                                                                        selectButton)
                                                                                                .addGap(0,
                                                                                                        0,
                                                                                                        Short.MAX_VALUE)))))
                                .addContainerGap())
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(addButton)
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(
                                                        metricField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectButton)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        13, Short.MAX_VALUE)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(
                                                        objectiveChoice,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(objectiveTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(
                                                        weightField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addButton).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void objectiveChoicePropertyChange(
            java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_objectiveChoicePropertyChange

    }// GEN-LAST:event_objectiveChoicePropertyChange

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
        if (objective == null) {
            return;
        }
        if (metric == null) {
            return;
        }

        double weight = Double.parseDouble(weightField.getText());
        TargetObjective to = new TargetObjective(metric.getSubstance(),
                objective, weight);
        psg.addTargetObjective(to);
        this.setVisible(false);
        parentFrame.setVisible(false);
        parentFrame.dispose();
    }// GEN-LAST:event_addButtonActionPerformed

    private void objectiveChoiceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_objectiveChoiceActionPerformed
        String function = (String) objectiveChoice.getSelectedItem();
        if (function.equalsIgnoreCase("Minimize")) {
            objective = new Minimize(metric);
        } else if (function.equalsIgnoreCase("Maximize")) {
            objective = new Maximize(metric);
        } else if (function.equalsIgnoreCase("Target Value")) {
            String targetInput = JOptionPane.showInputDialog(this,
                    "Target value?");
            double target = Double.parseDouble(targetInput);
            objective = new TargetValue(metric, target);
        } else if (function.equalsIgnoreCase("Match Expression/Substance")) {
            objective = new MatchSubstance(metric);
        }
        updateText();
    }// GEN-LAST:event_objectiveChoiceActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectButtonActionPerformed
        JFrame jf = new JFrame("Metric Selector");
        jf.getContentPane().add(new MetricEditor(jf, this));
        jf.pack();
        jf.show();
    }// GEN-LAST:event_selectButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField metricField;
    private javax.swing.JComboBox objectiveChoice;
    private javax.swing.JTextField objectiveTextField;
    private javax.swing.JButton selectButton;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
