/*
 * AnnotationEditor.java
 *
 * Created on May 7, 2005, 2:12 PM
 */

package dynetica.gui.entities;

/**
 * 
 * @author Lingchong You
 */
public class AnnotationEditor extends javax.swing.JPanel {
    private dynetica.entity.Annotation annotation;

    /**
     * Creates new form AnnotationEditor
     */
    public AnnotationEditor(dynetica.entity.Annotation annotation) {
        this.annotation = annotation;
        initComponents();
        annotationArea.setText(annotation.getAnnotation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sysLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        annotationArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        sysLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sysLabel.setText("About the system");
        add(sysLabel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 27));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 300));

        annotationArea.setLineWrap(true);
        annotationArea.setTabSize(5);
        annotationArea.setText(annotation.getAnnotation());
        annotationArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                annotationAreaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(annotationArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel2.add(saveButton);

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearButton);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearButtonActionPerformed
        annotationArea.setText("");
    }// GEN-LAST:event_clearButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetButtonActionPerformed
        annotationArea.setText(annotation.getAnnotation());
    }// GEN-LAST:event_resetButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveButtonActionPerformed
        annotation.setAnnotation(annotationArea.getText());
        annotation.getSystem().fireSystemStateChange();
    }// GEN-LAST:event_saveButtonActionPerformed

    private void annotationAreaFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_annotationAreaFocusLost
        // no need to do anything if focus is lost
        // annotation.setAnnotation(annotationArea.getText());
        // annotation.getSystem().fireSystemStateChange();
    }// GEN-LAST:event_annotationAreaFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea annotationArea;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sysLabel;
    // End of variables declaration//GEN-END:variables

}
